CREATE DATABASE IF NOT EXISTS perfumeria_smell
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `perfumeria_smell`.`admin_users` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `perfumeria_smell`.`perfumes` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slide TINYINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  brand VARCHAR(100) NOT NULL,
  price_5 DECIMAL(10,2) NOT NULL,
  price_10 DECIMAL(10,2) NOT NULL,
  image VARCHAR(255) NOT NULL,
  full_bottle TINYINT(1) NOT NULL DEFAULT 1,
  preserve_exact TINYINT(1) NOT NULL DEFAULT 0,
  stock_5 INT UNSIGNED NOT NULL DEFAULT 0,
  stock_10 INT UNSIGNED NOT NULL DEFAULT 0,
  stock_full INT UNSIGNED NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_perfume_name (name),
  INDEX idx_perfume_brand (brand),
  INDEX idx_perfume_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `perfumeria_smell`.`combos` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  type VARCHAR(180) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image VARCHAR(255) NOT NULL,
  items_json JSON NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `perfumeria_smell`.`settings` (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
