-- Canonical Supabase schema for Perfumería Smell.

-- Exported from migration 20260902022635 (initial_store_schema).

-- Apply through the Supabase migration workflow; never place secret/service-role keys in source control.



begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;

create table public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Administrador' check (char_length(display_name) between 2 and 100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.perfumes (
  id bigint generated by default as identity primary key,
  slide smallint not null check (slide > 0),
  name text not null check (char_length(name) between 1 and 160),
  brand text not null check (char_length(brand) between 1 and 100),
  price_5 numeric(10,2) not null check (price_5 >= 0),
  price_10 numeric(10,2) not null check (price_10 >= 0),
  image text not null check (char_length(image) > 0),
  full_bottle boolean not null default true,
  preserve_exact boolean not null default false,
  stock_5 integer not null default 0 check (stock_5 >= 0),
  stock_10 integer not null default 0 check (stock_10 >= 0),
  stock_full integer not null default 0 check (stock_full >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.combos (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (char_length(name) between 1 and 120),
  type text not null check (char_length(type) between 1 and 180),
  price numeric(10,2) not null check (price >= 0),
  image text not null check (char_length(image) > 0),
  items_json jsonb not null default '[]'::jsonb check (jsonb_typeof(items_json) = 'array'),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.settings (
  setting_key text primary key check (setting_key ~ '^[a-z][a-z0-9_]{1,79}$'),
  setting_value text not null,
  updated_at timestamptz not null default now()
);

create index perfumes_active_id_idx on public.perfumes (id) where active;
create index combos_active_id_idx on public.combos (id) where active;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.protect_exact_perfume_prices()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if old.preserve_exact then
    new.price_5 = old.price_5;
    new.price_10 = old.price_10;
    new.preserve_exact = true;
  end if;
  return new;
end;
$$;

revoke execute on function private.set_updated_at() from public, anon, authenticated, service_role;
revoke execute on function private.protect_exact_perfume_prices() from public, anon, authenticated, service_role;

create trigger admin_profiles_set_updated_at before update on public.admin_profiles
for each row execute function private.set_updated_at();
create trigger perfumes_set_updated_at before update on public.perfumes
for each row execute function private.set_updated_at();
create trigger perfumes_protect_exact_prices before update on public.perfumes
for each row execute function private.protect_exact_perfume_prices();
create trigger combos_set_updated_at before update on public.combos
for each row execute function private.set_updated_at();
create trigger settings_set_updated_at before update on public.settings
for each row execute function private.set_updated_at();

alter table public.admin_profiles enable row level security;
alter table public.perfumes enable row level security;
alter table public.combos enable row level security;
alter table public.settings enable row level security;

create policy admin_profiles_read_own
on public.admin_profiles for select to authenticated
using ((select auth.uid()) = user_id);

create policy perfumes_public_read_visible
on public.perfumes for select to anon, authenticated
using (
  active
  or exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy perfumes_admin_update
on public.perfumes for update to authenticated
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
)
with check (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy combos_public_read_visible
on public.combos for select to anon, authenticated
using (
  active
  or exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy combos_admin_update
on public.combos for update to authenticated
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
)
with check (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy settings_public_read
on public.settings for select to anon, authenticated
using (true);

create policy settings_admin_insert
on public.settings for insert to authenticated
with check (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy settings_admin_update
on public.settings for update to authenticated
using (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
)
with check (
  exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

revoke all on public.admin_profiles, public.perfumes, public.combos, public.settings from public, anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select on public.perfumes, public.combos, public.settings to anon;
grant select on public.admin_profiles, public.perfumes, public.combos, public.settings to authenticated;
grant update on public.perfumes, public.combos to authenticated;
grant insert, update on public.settings to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('catalog-media', 'catalog-media', true, 3145728, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy catalog_media_admin_select
on storage.objects for select to authenticated
using (
  bucket_id = 'catalog-media'
  and exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy catalog_media_admin_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'catalog-media'
  and exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy catalog_media_admin_update
on storage.objects for update to authenticated
using (
  bucket_id = 'catalog-media'
  and exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
)
with check (
  bucket_id = 'catalog-media'
  and exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

create policy catalog_media_admin_delete
on storage.objects for delete to authenticated
using (
  bucket_id = 'catalog-media'
  and exists (
    select 1 from public.admin_profiles ap
    where ap.user_id = (select auth.uid()) and ap.is_active
  )
);

notify pgrst, 'reload schema';
commit;

