<?php
declare(strict_types=1);
require_once __DIR__.'/../config/uploads.php';
require_once __DIR__.'/_header.php';
$message=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf();
  try{
    $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT); if(!$id)throw new RuntimeException('Perfume no válido.');
    $stmt=db()->prepare('SELECT * FROM perfumes WHERE id=?');$stmt->execute([$id]);$current=$stmt->fetch();if(!$current)throw new RuntimeException('Perfume no encontrado.');
    $name=trim((string)($_POST['name']??''));$brand=trim((string)($_POST['brand']??''));if($name===''||$brand==='')throw new RuntimeException('Nombre y marca son obligatorios.');
    $price5=(float)($_POST['price_5']??$current['price_5']);$price10=(float)($_POST['price_10']??$current['price_10']);
    if($price5<0||$price10<0)throw new RuntimeException('Los precios no pueden ser negativos.');
    if((int)$current['preserve_exact']===1){$price5=(float)$current['price_5'];$price10=(float)$current['price_10'];}
    $stock5=max(0,(int)($_POST['stock_5']??0));$stock10=max(0,(int)($_POST['stock_10']??0));$stockFull=max(0,(int)($_POST['stock_full']??0));$active=isset($_POST['active'])?1:0;
    $image=save_uploaded_image('image','uploads/products','perfume-'.$id)??$current['image'];
    $update=db()->prepare('UPDATE perfumes SET name=?,brand=?,price_5=?,price_10=?,stock_5=?,stock_10=?,stock_full=?,active=?,image=? WHERE id=?');
    $update->execute([$name,$brand,$price5,$price10,$stock5,$stock10,$stockFull,$active,$image,$id]);$message='Perfume actualizado correctamente.';
  }catch(Throwable $exception){$error=$exception->getMessage();}
}
$search=trim((string)($_GET['q']??''));$params=[];$sql='SELECT * FROM perfumes';if($search!==''){$sql.=' WHERE name LIKE ? OR brand LIKE ?';$params=["%$search%","%$search%"];} $sql.=' ORDER BY id';$stmt=db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$edit=null;if(isset($_GET['edit'])){$stmt=db()->prepare('SELECT * FROM perfumes WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch();}
?>
<h1>Perfumes</h1><p class="subtitle">Edita nombre, marca, stock, visibilidad e imagen. Los cuatro precios especiales permanecen bloqueados.</p><?php if($message):?><div class="notice ok"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<?php if($edit):?><section class="panel"><h2>Editar: <?=e($edit['name'])?></h2><form method="post" enctype="multipart/form-data" class="edit-grid"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$edit['id']?>"><label>Nombre<input name="name" required maxlength="160" value="<?=e($edit['name'])?>"></label><label>Marca<input name="brand" required maxlength="100" value="<?=e($edit['brand'])?>"></label><?php if((int)$edit['preserve_exact']===1):?><div class="locked wide">Los precios de este perfume pertenecen a las diapositivas 21, 24, 25 o 26 y están protegidos: 5 ml = <?=number_format((float)$edit['price_5'],0)?> Bs; 10 ml = <?=number_format((float)$edit['price_10'],0)?> Bs.</div><input type="hidden" name="price_5" value="<?=$edit['price_5']?>"><input type="hidden" name="price_10" value="<?=$edit['price_10']?>"><?php else:?><label>Precio 5 ml<input name="price_5" type="number" min="0" step="0.01" required value="<?=$edit['price_5']?>"></label><label>Precio 10 ml<input name="price_10" type="number" min="0" step="0.01" required value="<?=$edit['price_10']?>"></label><?php endif;?><label>Stock 5 ml<input name="stock_5" type="number" min="0" value="<?=$edit['stock_5']?>"></label><label>Stock 10 ml<input name="stock_10" type="number" min="0" value="<?=$edit['stock_10']?>"></label><label>Stock perfume completo<input name="stock_full" type="number" min="0" value="<?=$edit['stock_full']?>"></label><label>Nueva imagen (máx. 3 MB)<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label><label><span>Visibilidad</span><span><input name="active" type="checkbox" value="1" <?=$edit['active']?'checked':''?>> Mostrar en el catálogo</span></label><div class="wide toolbar"><button class="btn gold" type="submit">Guardar cambios</button><a class="btn light" href="perfumes.php">Cancelar</a></div></form></section><?php endif;?>
<section class="panel"><form class="toolbar" method="get"><input name="q" value="<?=e($search)?>" placeholder="Buscar perfume o marca"><button class="btn" type="submit">Buscar</button><?php if($search):?><a class="btn light" href="perfumes.php">Limpiar</a><?php endif;?></form><table class="admin-table"><thead><tr><th>Imagen</th><th>Perfume</th><th>5 ml</th><th>10 ml</th><th>Stock</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td data-label="Imagen"><img class="thumb" src="../<?=e(public_image($row['image']))?>" alt=""></td><td data-label="Perfume"><strong><?=e($row['name'])?></strong><br><span><?=e($row['brand'])?></span></td><td data-label="5 ml"><?=number_format((float)$row['price_5'],0)?> Bs</td><td data-label="10 ml"><?=number_format((float)$row['price_10'],0)?> Bs</td><td data-label="Stock"><?=$row['stock_5']?> / <?=$row['stock_10']?> / <?=$row['stock_full']?></td><td data-label="Estado"><?=$row['active']?'Visible':'Oculto'?><?=$row['preserve_exact']?' · Protegido':''?></td><td><a class="btn light" href="?edit=<?=$row['id']?><?= $search!==''?'&q='.urlencode($search):'' ?>">Editar</a></td></tr><?php endforeach;?></tbody></table></section>
<?php require __DIR__.'/_footer.php'; ?>
